In [38]:
# Importing the necessary packages
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import savefig

In [39]:
# Loading in the data set
df =pd.read_csv('csv_files/Model_Ready_Classification.csv', index_col=0, header=0)

In [40]:
df.head()

,H_FTPct,H_EFGPct,H_ThreePARt,H_FTR,H_REBPct,H_BLKPct,H_AST_TOV_Ratio,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio,Target
0,0.833,0.461538,0.395604,0.329670,0.506173,0.036585,1.785714,0.952,0.628049,0.463415,0.256098,0.493827,0.109890,2.142857,0
1,0.885,0.430851,0.404255,0.276596,0.538462,0.024390,1.133333,0.870,0.542683,0.414634,0.280488,0.461538,0.053191,2.266667,0
2,0.844,0.590909,0.428571,0.415584,0.486486,0.076923,2.500000,0.935,0.512821,0.397436,0.397436,0.513514,0.025974,1.812500,1
3,0.727,0.567568,0.364865,0.297297,0.475000,0.053333,2.000000,0.710,0.480000,0.453333,0.413333,0.525000,0.094595,1.727273,1
4,0.722,0.511905,0.369048,0.214286,0.540816,0.023810,2.363636,0.806,0.476190,0.511905,0.369048,0.459184,0.047619,3.166667,0

In [41]:
# Rearranging the columns before splitting again 
columns = ['H_FTPct', 'H_EFGPct', 'H_ThreePARt', 'H_FTR', 'H_REBPct', 'H_AST_TOV_Ratio', 
               'Target', 'A_FTPct', 'A_EFGPct', 'A_ThreePARt', 'A_FTR', 'A_REBPct', 'A_BLKPct', 
               'A_AST_TOV_Ratio']

In [42]:
df.columns

Index(['H_FTPct', 'H_EFGPct', 'H_ThreePARt', 'H_FTR', 'H_REBPct', 'H_BLKPct',
       'H_AST_TOV_Ratio', 'A_FTPct', 'A_EFGPct', 'A_ThreePARt', 'A_FTR',
       'A_REBPct', 'A_BLKPct', 'A_AST_TOV_Ratio', 'Target'],
      dtype='object')

In [43]:
# Changing the order of the colums
df = pd.DataFrame(df, columns = ['H_FTPct', 'H_EFGPct', 'H_ThreePARt', 'H_FTR', 'H_REBPct', 'H_BLKPct', 
                                     'H_AST_TOV_Ratio','Target', 'A_FTPct', 'A_EFGPct', 'A_ThreePARt', 
                                     'A_FTR', 'A_REBPct', 'A_BLKPct','A_AST_TOV_Ratio'])

In [44]:
df.head()

,H_FTPct,H_EFGPct,H_ThreePARt,H_FTR,H_REBPct,H_BLKPct,H_AST_TOV_Ratio,Target,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio
0,0.833,0.461538,0.395604,0.329670,0.506173,0.036585,1.785714,0,0.952,0.628049,0.463415,0.256098,0.493827,0.109890,2.142857
1,0.885,0.430851,0.404255,0.276596,0.538462,0.024390,1.133333,0,0.870,0.542683,0.414634,0.280488,0.461538,0.053191,2.266667
2,0.844,0.590909,0.428571,0.415584,0.486486,0.076923,2.500000,1,0.935,0.512821,0.397436,0.397436,0.513514,0.025974,1.812500
3,0.727,0.567568,0.364865,0.297297,0.475000,0.053333,2.000000,1,0.710,0.480000,0.453333,0.413333,0.525000,0.094595,1.727273
4,0.722,0.511905,0.369048,0.214286,0.540816,0.023810,2.363636,0,0.806,0.476190,0.511905,0.369048,0.459184,0.047619,3.166667

In [45]:
home = df.iloc[:,:8]

In [46]:
away = df.iloc[:,7:]

In [47]:
# Rearranging the columns before splitting again 
columns = ['A_FTPct', 'A_EFGPct', 'A_ThreePARt', 'A_FTR', 
           'A_REBPct', 'A_BLKPct', 'A_AST_TOV_Ratio', 'Target',]

In [48]:
# Changing the order of the colums
away = pd.DataFrame(away, columns = ['A_FTPct', 'A_EFGPct', 'A_ThreePARt', 'A_FTR', 
           'A_REBPct', 'A_BLKPct', 'A_AST_TOV_Ratio', 'Target',])

In [58]:
# Creating a function to bin the target variable
def target_binning(Target):
    if (Target) == 0:  # Will return 0 if a team loses the game
        return(1)
    else:                   # Will return 1 if a team wins the game
        return(0)

In [59]:
# Applying the function in order to bin the target variable 
away['New_Target'] = away['Target'].apply(target_binning)

In [60]:
away.head()

,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio,Target,New_Target
0,0.952,0.628049,0.463415,0.256098,0.493827,0.109890,2.142857,0,1
1,0.870,0.542683,0.414634,0.280488,0.461538,0.053191,2.266667,0,1
2,0.935,0.512821,0.397436,0.397436,0.513514,0.025974,1.812500,1,0
3,0.710,0.480000,0.453333,0.413333,0.525000,0.094595,1.727273,1,0
4,0.806,0.476190,0.511905,0.369048,0.459184,0.047619,3.166667,0,1

In [61]:
#Dropping the Old Target Variable
away = away.drop(['Target'], axis=1)

In [62]:
away.head()

,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio,New_Target
0,0.952,0.628049,0.463415,0.256098,0.493827,0.109890,2.142857,1
1,0.870,0.542683,0.414634,0.280488,0.461538,0.053191,2.266667,1
2,0.935,0.512821,0.397436,0.397436,0.513514,0.025974,1.812500,0
3,0.710,0.480000,0.453333,0.413333,0.525000,0.094595,1.727273,0
4,0.806,0.476190,0.511905,0.369048,0.459184,0.047619,3.166667,1

In [63]:
# Renaming the columns in order get ride of the % signs 
away.rename(columns={'New_Target':'Target'}, inplace=True)

In [64]:
away.head()

,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio,Target
0,0.952,0.628049,0.463415,0.256098,0.493827,0.109890,2.142857,1
1,0.870,0.542683,0.414634,0.280488,0.461538,0.053191,2.266667,1
2,0.935,0.512821,0.397436,0.397436,0.513514,0.025974,1.812500,0
3,0.710,0.480000,0.453333,0.413333,0.525000,0.094595,1.727273,0
4,0.806,0.476190,0.511905,0.369048,0.459184,0.047619,3.166667,1

In [65]:
home.head(1)

,H_FTPct,H_EFGPct,H_ThreePARt,H_FTR,H_REBPct,H_BLKPct,H_AST_TOV_Ratio,Target
0,0.833,0.461538,0.395604,0.32967,0.506173,0.036585,1.785714,0

In [66]:
away.head(1)

,A_FTPct,A_EFGPct,A_ThreePARt,A_FTR,A_REBPct,A_BLKPct,A_AST_TOV_Ratio,Target
0,0.952,0.628049,0.463415,0.256098,0.493827,0.10989,2.142857,1

In [67]:
home.count()

H_FTPct            9844
H_EFGPct           9844
H_ThreePARt        9844
H_FTR              9844
H_REBPct           9844
H_BLKPct           9844
H_AST_TOV_Ratio    9844
Target             9844
dtype: int64

In [68]:
away.count()

A_FTPct            9844
A_EFGPct           9844
A_ThreePARt        9844
A_FTR              9844
A_REBPct           9844
A_BLKPct           9844
A_AST_TOV_Ratio    9844
Target             9844
dtype: int64

In [70]:
# export working dataframe for Regression to csv
home.to_csv('csv_files/Home_Only_Classification.csv')
away.to_csv('csv_files/Away_Only_Classification.csv')